apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # CVE policies
  - ../cve/cve-constraint-template.yaml
  - ../cve/cve-constraint.yaml
  # Quality policies
  - ../quality/quality-constraint-template.yaml
  - ../quality/quality-constraint.yaml
