apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: engineering-platform
resources:
  - namespace.yaml
  - teams-api-alias.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
