# Starship Configuration
format = """
$username\
$hostname\
$kubernetes\
$docker_context\
$directory\
$git_branch\
$git_status\
$golang\
$nodejs\
$python\
$terraform\
$jobs\
$cmd_duration\
$line_break\
$character"""

right_format = """$time$battery$status$shell"""

scan_timeout = 100
command_timeout = 3000
follow_symlinks = false

[palettes.foo]
blue = '21'
mustard = '#af8700'

[username]
show_always = true
format = '[$user]($style) '
style_user = "fg:#F47A26"
style_root = "fg:#F47A26"

[hostname]
ssh_only = false
format = "[@$hostname]($style) "
style = "fg:#F47A26 bold"

[directory]
truncation_length = 3
truncate_to_repo = true
format = "[$path]($style)[$read_only]($read_only_style) "
style = "bg:none fg:#F47A26 bold"
home_symbol = "~"
truncation_symbol = "â€¦/"

[git_branch]
format = '[$symbol$branch]($style) '
symbol = ""
style = "bold purple"
truncation_length = 18

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'
conflicted = "!"
ahead = "â†‘${count}"
diverged = "â†•${ahead_count}â†“${behind_count}"
behind = "â†“${count}"
up_to_date = "âœ“"
untracked = "?${count}"
stashed = "*${count}"
modified = "~${count}"
staged = '+${count}'
renamed = "â†’${count}"
deleted = "âœ—${count}"
style = "bold red"

[kubernetes]
symbol = "âˆ "
format = '[$symbol$context( @$namespace)]($style) '
style = "cyan bold"
disabled = false
detect_files = ['k8s', 'kubernetes']
detect_folders = ['.kube']

[[kubernetes.contexts]]
context_pattern = ".*pangarabbit.*"
context_alias = "pgr"
style = "bold cyan"

[[kubernetes.contexts]]
context_pattern = ".*infra.*"
context_alias = "dev"
style = "bold green"

[[kubernetes.contexts]]
context_pattern = ".*nonprod.*"
context_alias = "test"
style = "bold yellow"

[[kubernetes.contexts]]
context_pattern = ".*prod.*"
context_alias = "prod"
style = "bold red"

[docker_context]
format = "[$symbol$context]($style) "
symbol = "ğŸ³ "
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
style = "blue bold"

[cmd_duration]
min_time = 5_000
format = "â± [$duration]($style) "
style = "bold yellow"

[character]
success_symbol = "[âœ](bold green) "
error_symbol = "[âœ—](bold red) "
vicmd_symbol = "[â†](bold green)"

[golang]
format = "[$symbol($version )]($style)"
symbol = "ğŸ¹ "

[nodejs]
format = "[$symbol($version )]($style)"
symbol = "â¬¢ "

[python]
format = "[$symbol($version )]($style)"
symbol = "ğŸ "

[terraform]
format = '[$symbol$workspace]($style) '
symbol = "TF:"
detect_folders = [".terraform"]
style = "bold_105"

[time]
disabled = false
format = "ğŸ•™[$time]($style) "
time_format = "%H:%M"
style = "bold white"

[battery]
disabled = true

[status]
disabled = true

[shell]
disabled = true
